### ISSUE TITLE
Move metal emissions to branch

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#122]
https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/87434872d0eb17c4fc5d3c78b76704a6f34cdd92/fedelemflowlist/subset_list.py#L165

**Comment by bl-young** [comment]
Because of this [line](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/master/fedelemflowlist/subset_list.py#L21), that function is not accessible.
``           #"metal_emissions":"get_metal_emission_flows",``

but if you'd like I can move the whole function to a new branch

**Comment by WesIngwersen** [comment]
yea i figured just move the whole function

**Comment by bl-young** [comment]
moved to branch subset_list
