### ISSUE TITLE
problems installing

### ISSUE THREAD

**Issue by mfastudillo** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#123]
Hi!

I have tried to [install ](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/wiki/GitHub-Contributors#install-for-users)the package as outlined in the instructions in a new conda virtual environment and I get the following error message:

pip install git+https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List.git@v1.0#egg=Federal-LCA-Commons-Elementary-Flow-List

Collecting Federal-LCA-Commons-Elementary-Flow-List
  Cloning https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List.git (to revision v1.0) to c:\users\migue\appdata\local\temp\pip-install-1omv9nzh\federal-lca-commons-elementary-flow-list_7cc046fedf48446e99192e8920d09c60
  Running command git clone -q https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List.git 'C:\Users\migue\AppData\Local\Temp\pip-install-1omv9nzh\federal-lca-commons-elementary-flow-list_7cc046fedf48446e99192e8920d09c60'
  Running command git checkout -q d3cba44e8d9c36dd3e1e2aa4e05b322fb8e8d94e
  WARNING: Generating metadata for package Federal-LCA-Commons-Elementary-Flow-List produced metadata for project name fedelemflowlist. Fix your #egg=Federal-LCA-Commons-Elementary-Flow-List fragments.
WARNING: Discarding git+https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List.git@v1.0#egg=Federal-LCA-Commons-Elementary-Flow-List. Requested fedelemflowlist from git+https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List.git@v1.0#egg=Federal-LCA-Commons-Elementary-Flow-List has inconsistent name: filename has 'federal-lca-commons-elementary-flow-list', but metadata has 'fedelemflowlist'
ERROR: Could not find a version that satisfies the requirement federal-lca-commons-elementary-flow-list (unavailable) (from versions: none)
ERROR: No matching distribution found for federal-lca-commons-elementary-flow-list (unavailable)

I get a similar error if I try to install version 1.0.7 . The environment has already an updated version of pip and pyarrow installed. (python version 3.9.5)

**Comment by bl-young** [comment]
Sorry the egg indicated in the wiki was incorrect, the correct command is 
`pip install git+https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List.git@v1.0#egg=fedelemflowlist`

I have updated the wiki. And yes we recommend the latest version (1.0.7).

Note if you are installing lciafmt, the correct fedelemflowlist should get installed then.
