### ISSUE TITLE
SimaPro/brightway2/ecoinvent support?

### ISSUE THREAD

**Issue by MaximeAgez** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#134]
Hello,
I was wondering if there already are mappings from the FEDEFL flows to the flow nomenclature used in SimaPro and brightway2/ecoinvent?
For some context, I am looking to connect an LCIA method to the FEDEFL list (through LCIAformatter) to then easily be able to distribute the LCIA method to the different LCA software. So if the work, or at least a part of the work, has already been done that would help me out greatly.
Thanks!

**Comment by WesIngwersen** [comment]
Hi @MaximeAgez. Mappings from FEDEFL to Ecoinvent have been completed via a UNEP GLAD Nomenclature project. cc @ashleyedelen. They are under review and once approved will be housed in this [Elementary Flow Resources](https://github.com/UNEP-Economy-Division/GLAD-ElementaryFlowResources) repo under UNEP. 

I would recommend discussing the brightway connection with the Brightway developers list via 
development@brightway.groups.io  . Chris Mutel mentioned that as being a possible direction but I have not heard more. 

A FEDEFL<->SimaPro mapping would be great, but I am unaware of any initiative to create one.

**Comment by WesIngwersen** [comment]
@MaximeAgez If there is strong interest from your organization and want to discuss the topic more in depth, you are welcome to [email me ](ingwersen.wesley@epa.gov) and we can set up a time and involve others that would be valuable to the discussion. thanks
