### ISSUE TITLE
Add Jobs and Value Added to subsets

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#145]

**Comment by bl-young** [comment]
Those are not flows in the list. Do you think we should go ahead and add them?

In the past we've been able to map to them to change the name, but there is no UUID at this point. I think that will be needed to add them to the subset list

**Comment by WesIngwersen** [comment]
can close for now... have some doubts about the need for it after further consideration.  thanks @bl-young for your feedback
