### ISSUE TITLE
Broken installation for previous versions

### ISSUE THREAD

**Issue by dt-woods** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#162]
Something happened and now I can no longer install this Python package using the following command. What happened?

```
pip install git+https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List@v1.0.2#egg=fedelemflowlist
```

See error screenshot:

<img width="736" alt="Screen Shot 2023-06-12 at 13 29 44" src="https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/assets/29642997/8888c742-9844-4219-8665-952bb00b0bdb">

**Comment by dt-woods** [comment]
Also, why is git-lfs now a requirement? I don't see it in your README, requirements list, or instructions Wiki.

**Comment by bl-young** [comment]
It looks like its having issues with `wiki/Resources/FEDEFLContexts.xlsx` which did not exist in v1.0.2. Perhaps try deleting that file to install v1.0.2?

> Also, why is git-lfs now a requirement? I don't see it in your README, requirements list, or instructions Wiki.

I don't believe git-lfs should be required to install the package, did you get an indication that it was?

**Comment by dt-woods** [comment]
> It looks like its having issues with wiki/Resources/FEDEFLContexts.xlsx which did not exist in v1.0.2. Perhaps try deleting that file to install v1.0.2?

This error was prompted in a fresh Python virtualenv, so there's nothing for me to delete.

> I don't believe git-lfs should be required to install the package, did you get an indication that it was?

Yeah. A colleague of mine tried installing and got an error pointing to git-lfs.

**Comment by bl-young** [comment]
Is this still an issue @dt-woods - are you still having issues if you try to install a more recent version of the flow list?

The file indicated in this issue was added after v1.0.2 so I'm not exactly sure why it would be looking for it.

**Comment by bl-young** [comment]
I believe the solution here is to not install v1.0.2. We always recommend using the latest version. So I am going to close this issue given the work underway in https://github.com/USEPA/ElectricityLCI/issues/196

**Comment by dt-woods** [comment]
No. We used a work-around downloading the .zip and running the setup.py manually. As you said, we shouldn't need it with the next release of electricityLCI.
