### ISSUE TITLE
Flow mapping

### ISSUE THREAD

**Issue by bl-young** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#37]
When using the flow mapping feature (in v1.10 or the public version of 1.9) the source category and target category fields add extra spaces even if no spaces are included in the mapping csv file. This causes openLCA not to recognize the category correctly

When editing the source flow and target flow manually and selecting the flow in the database, the category is fixed (see highlighted row in image) and the status is confirmed. This does not seem to impact the actual mapping, only the status.

![image](https://user-images.githubusercontent.com/44471635/69735369-940f7500-10fe-11ea-8812-02f7f67a8cbb.png)

**Comment by WesIngwersen** [comment]
@bl-young As I understand it, this is an openLCA issue. I recommend posting it @GreenDelta/olca-app and emailing GreenDelta.

**Comment by bl-young** [comment]
@msrocka cross-posting to olca-app
