### ISSUE TITLE
USLCI mappings: Not all flows mapped to flows in list error

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#48]
When running `add_uuid_to_flowmapping.py`

**Comment by bl-young** [comment]
Correct - the version I pushed includes the unmappable flows.

**Comment by WesIngwersen** [comment]
@bl-young Running `add_uuid_to_flowmapping.py`  actually chops off any mappings without flow matches.. when I ran it a second time I didn't get the error. Is there are reason you need to include the unmapped flows in this mapping? If we were to allow that our flowmappings tests as well as that script would have to be modify or else they will throw errors

**Comment by bl-young** [comment]
We decided to include them for completeness for the Q4 database; explicit non-matches. But there is no reason why it needs to stay that way.

I've confirmed that the list before and after adding UUID matches what we expect.

**Comment by WesIngwersen** [comment]
Let's just preserve the non-matches somewhere else - I agree it's important to record them, but just somewhere else where it won't break the tests.

**Comment by bl-young** [comment]
OK - would you like me to commit the revised file or do you have it there?

**Comment by WesIngwersen** [comment]
I've done it and closing this issue, thanks.
