### ISSUE TITLE
Check TRACI metal mappings

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#50]
TRACI generally has metal ions and FEDEFL metals without charge.  This results in a lack of mapping to a number of CFs in TRACI for these ions. Some examples

LEAD(II) - TRACI
Lead - FEDEFL

ANTIMONY(III), ANTIMONY(V) - TRACI
Antimony - FEDEFL

This needs to be consider for mapping purposes.

**Comment by hottleta** [comment]
I found this to be true with the Lead example, but the two Antimony flows appear to be mapped correctly.

**Comment by bl-young** [comment]
Flow list and TRACI mapping updated with Troy's changes. Will run LCIAformatter to confirm fixed

**Comment by bl-young** [comment]
Need to assess whether characterization factors should remain for the metals (e.g. lead), especially if they are used by EPA datasets like NEI/TRI. WE may want to duplicate TRACI flowables mapping:
LEAD(II) --> Lead
LEAD(II) --> Lead(II)

**Comment by bl-young** [comment]
@WesIngwersen This is resolved #55
