### ISSUE TITLE
Updating List

### ISSUE THREAD

**Issue by ashleyedelen** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#62]
Flows that have been updated in our defining sources that are in our list in a as the systematic name and not the chemistry dashboard name

Allyl alcohol versus 2-Propen-1-ol
Cuprammonium acetate versus Copper,   bis(acetato-.kappa.O)diammine-

**Comment by ashleyedelen** [comment]
(systematic) Ethane, 2-(difluoromethoxy)-1,1,1,2-tetrafluoro-, (+-)- is the same as (chemistry dashboard) Desflurane & 1,2,2,2-tetrafluoroethyl difluoromethyl ether
(systematic) Ethane, 1,1-difluoro-2-(trifluoromethoxy)- is the same as (chemdash) 1,1-Difluoro-2-(trifluoromethoxy)ethane

**Comment by bl-young** [comment]
@ashleyedelen See #65 

Please confirm that I've added the above flows correctly. Let's add to that list here as more are identified. When they are updated in the flows list we should identify that with the version number in this file.
