### ISSUE TITLE
Flow property mismatch in mapping

### ISSUE THREAD

**Issue by bl-young** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#87]
In rare cases, flows will have the same unit but different flow properties (e.g. net caloric value v. energy). Mapping files, nor the FEDEFL specify the flow property, I believe it is assumed from the unit.

When flow properties don't match when performing a mapping using the flow tool, it triggers an error

**Comment by bl-young** [comment]
Flow properties are assigned to both source and target flows [here](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/master/fedelemflowlist/jsonld.py#L79) which is a function of the unit. In this case, Energy gets set as the flow property for both source and target flow, despite the source flow being in Net Calorific Value. In the current setup of the mapping file, there is no way to indicate an alternative. 

This may need to be addressed within the tool itself, perhaps [here](https://github.com/GreenDelta/olca-app/blob/master/olca-app/src/org/openlca/app/tools/mapping/model/Sync.java#L49)

**Comment by bl-young** [comment]
@msrocka is there a reason that the flow property check is necessary in the mapping tool when units are also checked? Or alternatively could this be adjusted to a warning instead of an error so the mapping can still proceed.

Some examples of the issue from mapping the olca ref flow list to FEDEFL:

Status | Source flow | Source category | Target flow | Target category | Conversion factor
-- | -- | -- | -- | -- | --
source flow: the flow in the database has   no corresponding flow property | natural gas;  44.1 MJ/kg | Elementary flows/Resource/in ground | Natural gas | resource/air/subterranean | 1.00000 MJ/MJ
source flow: the flow in the database has   no corresponding flow property | biomass;  14.7 MJ/kg | Elementary flows/Resource/biotic | Biomass | resource/biotic | 0.05941 kg (Mass)/MJ (Energy)
source flow: the flow in the database has   no corresponding flow property | Biotic Production | Elementary flows/Resource/land | Biomass | resource/biotic | 1.00000 kg/kg
source flow: the flow in the database has   no corresponding flow property | wood;  14.7 MJ/kg | Elementary flows/Resource/biotic | Wood | resource/biotic | 0.04951 kg (Mass)/MJ (Energy)

**Comment by msrocka** [comment]
We could change this check into a warning but this then also needs changes in the calculation of the conversion factors when replacing the flows in the database. The reason for this is that an exchange amount (or characterization factor) can be given in any combination of unit and flow property that the flow allows which can be different than the combination for which the mapping is defined. As a flow in openLCA can have different flow properties that are linked to the same unit group we also need the flow property for calculating that factor correctly. [Implementation is here](https://github.com/GreenDelta/olca-app/blob/master/olca-app/src/org/openlca/app/tools/mapping/replacer/FactorProvider.java#L56)

I think a maybe better way to fix this is to not write the flow property references (which obviously cannot always correctly inferred from the unit) of the source flows into the mapping file ([probably
here](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/master/fedelemflowlist/jsonld.py#L79)). The mapping tool [should then already take the reference flow property](https://github.com/GreenDelta/olca-app/blob/master/olca-app/src/org/openlca/app/tools/mapping/model/DBProvider.java#L107) of the flow in the openLCA database.

**Comment by bl-young** [comment]
That makes sense to me. So if we remove the assignment of flow property within the mapping json it will get assigned by the mapping tool automatically. Thanks I will give that a try.

**Comment by bl-young** [comment]
Thanks that did the trick.
