### ISSUE TITLE
Duplicate records in TRI mapping file

### ISSUE THREAD

**Issue by bl-young** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#99]
There are a number of duplicate entries in the TRI mapping file e.g. [ACETOPHENONE ](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/master/fedelemflowlist/flowmapping/TRI.csv#L964)

**Comment by hottleta** [comment]
@bl-young the new approach developed in 'context_mapping' branch should solve this issue, right?

**Comment by bl-young** [comment]
Only if we drop duplicates in the source files. https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/commit/e5b5340305345d54c78037d07883f414b0103ed7

**Comment by hottleta** [comment]
In the new input files we don't have any exact duplicates. We do have some that are all CAPS and some that aren't but I believe those need to be mapped separately.
